### ISSUE TITLE
ts3client installed from PPA doesn't start in Ubuntu 18.04

### ISSUE THREAD

**Issue by logix2** [BeardOverflow/ts3client-deb#2]
ts3client doesn't start in Ubuntu 18.04 (I didn't try other Ubuntu versions). I installed it from the PPA. When launched, the app displays an error about failing to load ca certificates: [https://i.imgur.com/aWM0F2H.png](https://i.imgur.com/aWM0F2H.png)

**Comment by logix2** [comment]
I managed to find a workaround which I think should be integrated in your packages since it can't work without this. 

The ts3client launch script has this:
```
  #Is cert.pem located there?
  if [ -f "${OPENSSL_DIR}/cert.pem" ]
  then
    #Use this file
    export SSL_CERT_FILE=${OPENSSL_DIR}/cert.pem
```
On Ubuntu, the OpenSSL cert file is located in ``/etc/ssl/certs/`` and is called ``ca-certificates.crt`` so I guess the script should be updated to use this on Ubuntu.

An alternative to modifying this is to launch the app like this:
```
SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt ts3client 
```

**Comment by BeardOverflow** [comment]
I am trying to reproduce your issue in a Ubuntu 18.04 newly installed, but I do not able to.

1. Could you check if you have installed the package ca-certificates and which version is it?
```
ubuntu@bionic:~$ dpkg -l | grep ca-certificates
ii ca-certificates   20180409 all Common CA certificates
```

2. Could you check if you get a similar output using this command?
```
ubuntu@bionic:~$ echo `openssl version -d | grep -Po '(?<=\").*(?=\")'`
/usr/lib/ssl
ubuntu@bionic:~$ openssl version
OpenSSL 1.1.0g  2 Nov 2017
```

3. Could you check if both files /etc/ssl/certs/ca-certificates.crt and /usr/lib/ssl/certs/ca-certificates.crt exist and they are the same file?
```
ubuntu@bionic:~$ ls -laih /usr/lib/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
1109 -rw-r--r-- 1 root root 203K Aug 29 15:55 /etc/ssl/certs/ca-certificates.crt
1109 -rw-r--r-- 1 root root 203K Aug 29 15:55 /usr/lib/ssl/certs/ca-certificates.crt
ubuntu@bionic:~$ diff /usr/lib/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
```

4. And finally, could you regenerate the ca-certificates files like a trigger in a Debian package?
```
ubuntu@bionic:~$ sudo update-ca-certificates -d
Clearing symlinks in /etc/ssl/certs...
done.
Updating certificates in /etc/ssl/certs...
133 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
```

**Comment by logix2** [comment]
Thank you for your response. ``sudo update-ca-certificates -d`` got it to work. Since I had ``ca-certificates`` installed, I didn't imagine I have to do anything else. Weird...

Thanks again!
